#!/bin/sh
set -eu
version="0.2.1"

usage() {
  cat <<__USAGE__ >&2
Usage: ${0##*/} [OPTION]... {script-only-if-no-other-script} [input-file]...
Edit text with Vim script.

Options:
  -n, --quiet, --silent
                 suppress automatic printing of buffer
  -e script, --expression=script
                 add the script to the commands to be executed
  -f script-file, --file=script-file
                 add the contents of script-file to the commands to be executed
  --help
                 display this help and exit
  --version
                 display version information and exit
__USAGE__
}

version() {
  printf "%s\n" "$version" >&2
}

warn() {
  printf "%s: %s\n" "${0##*/}" "$*" >&2
}

script=$(mktemp "/tmp/${0##*/}.tmp.XXXXXX")
src=$(mktemp "/tmp/${0##*/}.tmp.XXXXXX")
atexit() {
	rm -f -- "$script" "$src"
}
trap "atexit" EXIT
trap "trap - EXIT; atexit; exit -1" INT PIPE TERM

require_print=1
require_program=1
while [ $# -gt 0 ]; do
  case $1 in
    --help)
      usage
      exit 0
      ;;
    --version)
      version
      exit 0
      ;;
    -n|--quiet|--silent)
      require_print=0
      ;;
    -n*)
      require_print=0
      next=-${1#-n}
      shift
      set -- "$next" "$@"
      continue
      ;;
    -e|--expression)
      require_program=0
      if [ $# -lt 2 ]; then
        warn "option requires an argument -- '${1##*-}'"
        exit 2
      fi
      printf "%s\n" "$2" >> "$script"
      shift
      ;;
    -e*)
      require_program=0
      printf "%s\n" "${1#-e}" >> "$script"
      ;;
    --expression=*)
      require_program=0
      printf "%s\n" "${1#--expression=}" >> "$script"
      ;;
    -f|--file)
      require_program=0
      if [ $# -lt 2 ]; then
        warn "option requires an argument -- '${1##*-}'"
        exit 2
      fi
      cat -- "$2" >> "$script"
      shift
      ;;
    -f*)
      require_program=0
      cat -- "${1#-f}" >> "$script"
      ;;
    --file=*)
      require_program=0
      cat -- "${1#--file=}" >> "$script"
      ;;
    --)
      shift
      break
      ;;
    -*)
      warn "unrecognized option '$1'"
      exit 2
      ;;
    *)
      break
      ;;
  esac
  shift
done
if [ $require_program -eq 1 ]; then
  if [ $# -lt 1 ]; then
    usage
    exit 2
  fi
  printf "%s\n" "$1" >> "$script"
  shift
fi
if [ $require_print -eq 1 ]; then
  echo "%print" >> "$script"
fi
echo "qall!" >> "$script"

cat -- "$@" > "$src"
vim -u NONE -i NONE -N -n -e -s -S "$script" -- "$src"
exit 0
