#! /bin/sh
set -eu

usage() {
  cat <<__USAGE__ 1>&2
Usage: ${0##*/} [OPTION]... PROGRAM [FILE]...
Edit text with Vim script.

Options:
      --help     display this help and exit
__USAGE__
}

if [ "$#" -lt 1 ]; then
  echo "Usage: ${0##*/} [OPTION]... PROGRAM [FILE]..."  1>&2
  exit 2
elif [ "$1" = "--help" ]; then
  usage
  exit 0
fi
program="$1"
shift

script="$(mktemp)"
src="$(mktemp)"
trap 'rm '$script' '$src EXIT

cat -- "$@" > "$src"
echo "$program" >> "$script"
echo "%print" >> "$script"
echo "exit" >> "$script"
vim -u NONE -i NONE -N -n -e -s -S "$script" "$src"
